---
# - hosts: xenials
#   gather_facts: False
#   become: yes
#   tasks:
#     - name: Check python install
#       raw: which python
#       register: python_installed
#       ignore_errors: yes

#     - name: apt-get update
#       raw: apt-get update -qq
#       when: not python_installed.rc == 0

#     - name: Install python 2.7
#       raw: apt-get install -qq python2.7
#       when: not python_installed.rc == 0

#     - name: Link Python 2.7
#       raw: sudo ln -s /usr/bin/python2.7 /usr/bin/python
#       when: not python_installed.rc == 0

- hosts: mgmt
  become: yes
  roles:
    - mgmt
  handlers:
    - include: handlers/main.yml
      static: yes
  tags: server

- hosts: spine
  become: yes
  roles:
    - monitoring_agent
  handlers:
    - include: handlers/main.yml
      static: yes
  tags:
    - spine
    - fabric

- hosts: leaf
  become: yes
  roles:
    - monitoring_agent
  handlers:
    - include: handlers/main.yml
      static: yes
  tags:
    - spine
    - fabric
