---
- name: Install Kapacitor
  apt:
    deb: https://dl.influxdata.com/kapacitor/releases/kapacitor_1.4.0_amd64.deb

- name: Apply Kapacitor configuration
  template: src=kapacitor.conf.j2 dest=/etc/kapacitor/kapacitor.conf backup=yes
  notify: restart kapacitor

- name: Start Kapacitor if not started
  service: name=kapacitor state=started

- name: copy alerting tick script
  copy: src=kapacitor_checks/{{ item.script }} dest=/etc/kapacitor/checks/
  with_items:
    - { script: "bgp_failed_peers.tick" }

- name: install alerting tick scripts into kapacitor
  command: kapacitor define {{ item.name }} -type stream -tick /etc/kapacitor/checks/{{ item.script}} -dbrp "network"."autogen"
  with_items:
    - { name: "bgp_failed_peers", script: "bgp_failed_peers.tick"}

- name: enable alerting scripts
  command: kapacitor enable {{ item.name }}
  with_items:
    - { name: "bgp_failed_peers", script: "bgp_failed_peers.tick"}
